// This file is automatically generated. Do not modify it manually.

package main

import (
	"strings"

	"github.com/mattermost/mattermost-server/v5/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.github.muratbayan.mattermost-quickchart",
  "name": "Quickchart",
  "description": "This plugin serves as a starting point for writing a Mattermost plugin.",
  "version": "0.1.1",
  "min_server_version": "5.12.0",
  "server": {
    "executables": {
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "TestConfigItem",
        "display_name": "Test Config Item",
        "type": "text",
        "help_text": "Just a config Item - String",
        "placeholder": "",
        "default": "WirSindDieRoboter"
      }
    ]
  }
}
`

func init() {
	manifest = model.ManifestFromJson(strings.NewReader(manifestStr))
}
